#ifndef DISPLAY_CONFIG_H_
#define DISPLAY_CONFIG_H_

#include "settings.h"

/* LCD SETTINGS */


typedef enum
{
	DISPLAY_OPERATOR = 1,
	DISPLAY_CUSTOMER = 0,
	DISPLAY_BOTH = 2,
	DISPLAY_COUNT = DISPLAY_BOTH

} DISPLAY;

// unused
//#define DISPLAY_OPERATOR_WELCOME_MESSAGE	"   TRING  ONE"
//#define DISPLAY_CUSTOMER_WELCOME_MESSAGE	"   TRING  ONE"

#define LCD_RESET_PORT			GPIOB
#define LCD_RESET_PIN			GPIO_Pin_2
#define LCD_RESET_ON		    gpio_set_pin(LCD_RESET_PORT, LCD_RESET_PIN)
#define LCD_RESET_OFF		    gpio_reset_pin(LCD_RESET_PORT, LCD_RESET_PIN)

#define LCD_BACKLIGHT_PORT		GPIOA
#define LCD_BACKLIGHT_PIN		GPIO_Pin_7
#define LCD_BACKLIGHT_ON		gpio_set_pin(LCD_BACKLIGHT_PORT, LCD_BACKLIGHT_PIN)
#define LCD_BACKLIGHT_OFF		gpio_reset_pin(LCD_BACKLIGHT_PORT, LCD_BACKLIGHT_PIN)

#define OPERATOR_DISPLAY_I2C_REG	I2C1
#define CUSTOMER_DISPLAY_I2C_REG	I2C2
/* END OF LCD */

#endif /* DISPLAY_CONFIG_H_ */
