#ifndef PERIPHERAL_CONFIG_H_
#define PERIPHERAL_CONFIG_H_

#include "settings.h"

/* PERIPHERAL SETTINGS */
#define PERIPHERAL_DEVICE_SLEEP				(1 << 0)
#define PERIPHERAL_DEVICE_LCD			 	(1 << 1)
#define PERIPHERAL_DEVICE_TOUCH				(1 << 2)
#define PERIPHERAL_DEVICE_SD				(1 << 3)
#define PERIPHERAL_DEVICE_MODEM				(1 << 4)
#define PERIPHERAL_DEVICE_PRINTER			(1 << 5)
#define PERIPHERAL_DEVICE_BARCODE_READER	(1 << 6)
#define PERIPHERAL_DEVICE_RTC				(1 << 7)
#define PERIPHERAL_DEVICE_EEPROM			(1 << 8)
#define PERIPHERAL_DEVICE_FM				(1 << 9)
#define PERIPHERAL_DEVICE_SRAM				(1 << 10)
#define PERIPHERAL_DEVICE_KEYBOARD			(1 << 11)
#define PERIPHERAL_DEVICE_HSI_CLOCK			(1 << 12)
#define PERIPHERAL_DEVICE_HSI48_CLOCK		(1 << 13)
#define PERIPHERAL_DEVICE_POWER				(1 << 14)

#define PERIPHERAL_DEVICE_ALL				(0xFFFF)

#define PERIPHERAL_ERROR_DEVICE_NOTIFICATION_1		PERIPHERAL_DEVICE_LCD
#define PERIPHERAL_ERROR_DEVICE_NOTIFICATION_2		PERIPHERAL_DEVICE_PRINTER
#define PERIPHERAL_ERROR_DEVICE_NOTIFICATION_3		PERIPHERAL_DEVICE_LCD

#define PERIPHERAL_POWER_CLOCK				RCC_AHBPeriph_GPIOC
#define PERIPHERAL_POWER_PORT				GPIOC
#define PERIPHERAL_POWER_PIN				GPIO_Pin_0
#define PERIPHERAL_POWER_ON					gpio_reset_pin(PERIPHERAL_POWER_PORT,PERIPHERAL_POWER_PIN)
#define PERIPHERAL_POWER_OFF				gpio_set_pin(PERIPHERAL_POWER_PORT,PERIPHERAL_POWER_PIN)

#define PERIPHERAL_SERVICE_PORT				GPIOA
#define PERIPHERAL_SERVICE_PIN				GPIO_Pin_3
#define PERIPHERAL_SERVICE_PIN_STATUS		!(gpio_read_pin(PERIPHERAL_SERVICE_PORT, PERIPHERAL_SERVICE_PIN))

//#define PERIPHERAL_LED_GREEN_PORT			GPIOB
//#define PERIPHERAL_LED_GREEN_PIN			GPIO_Pin_12
//#define PERIPHERAL_LED_GREEN_ON				gpio_set_pin(PERIPHERAL_LED_GREEN_PORT,PERIPHERAL_LED_GREEN_PIN)
//#define PERIPHERAL_LED_GREEN_OFF			gpio_reset_pin(PERIPHERAL_LED_GREEN_PORT,PERIPHERAL_LED_GREEN_PIN)

#define PERIPHERAL_LED_RED_PORT				GPIOB
#define PERIPHERAL_LED_RED_PIN				GPIO_Pin_14
#define PERIPHERAL_LED_RED_ON				gpio_set_pin(PERIPHERAL_LED_RED_PORT,PERIPHERAL_LED_RED_PIN)
#define PERIPHERAL_LED_RED_OFF				gpio_reset_pin(PERIPHERAL_LED_RED_PORT,PERIPHERAL_LED_RED_PIN)

#define PERIPHERAL_CASH_DRAWER_CLOCK		RCC_AHBPeriph_GPIOB
#define PERIPHERAL_CASH_DRAWER_PORT			GPIOB
#define PERIPHERAL_CASH_DRAWER_PIN			GPIO_Pin_1
#define PERIPHERAL_CASH_DRAWER_ON			gpio_set_pin(PERIPHERAL_CASH_DRAWER_PORT,PERIPHERAL_CASH_DRAWER_PIN)
#define PERIPHERAL_CASH_DRAWER_OFF			gpio_reset_pin(PERIPHERAL_CASH_DRAWER_PORT,PERIPHERAL_CASH_DRAWER_PIN)
#define PERIPHERAL_CASH_DRAWER_TIMEOUT		500


/* END OF PERIPHERAL SETTINGS */


#endif
